# Generated by Django 2.1.7 on 2019-05-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_storybone'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_finish',
            field=models.CharField(choices=[('false', '物語は続く'), ('true', '物語の終了')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
